import asyncio
import datetime
import logging
import secrets
import time
import uuid
from typing import Dict, List, Optional, Tuple
import httpx

from app.config import settings
from app.schemas import (
    FileItemResponse,
    JobCreateRequest,
    JobResponse,
)
from app.services.docker_manager import RunnerContainerRecord, docker_manager

logger = logging.getLogger("worker.job_service")


class JobService:
    def __init__(self):
        self.jobs: Dict[str, JobResponse] = {}
        self._sync_tasks: Dict[str, asyncio.Task] = {}
        # Maps file_id (hex) or filename -> (filename, container_id)
        self.file_map: Dict[str, Tuple[str, Optional[str]]] = {}
        # Single-use tokens for job creation: token -> (expiry timestamp, Optional[user_id])
        self.single_use_tokens: Dict[str, Tuple[float, Optional[str]]] = {}
        # Job tracking tokens: job_id -> tracking_token
        self.job_tracking_tokens: Dict[str, str] = {}
        # Downloaded files tracking: job_id -> set of downloaded file_ids/filenames
        self.downloaded_files: Dict[str, set] = {}

    def generate_single_use_token(self, expires_in: int = 300, user_id: Optional[str] = None) -> str:
        self._cleanup_expired_tokens()
        token = secrets.token_urlsafe(32)
        self.single_use_tokens[token] = (time.time() + expires_in, user_id)
        return token

    def validate_and_consume_single_use_token(self, token: Optional[str]) -> Tuple[bool, Optional[str]]:
        if not token:
            return False, None

        from app.services.announcer import announcer
        from app.services.crypto import worker_crypto

        # 1. Verify orchestrator-issued cryptographic token
        valid, payload = worker_crypto.verify_and_consume_token_with_payload(
            token=token,
            expected_worker_id=announcer.worker_id,
            auth_token=announcer.auth_token,
        )
        if valid and payload:
            return True, payload.get("user_id")
        elif valid:
            return True, None

        # 2. In dev/test mode without announcer auth_token, also verify token structure
        if not announcer.auth_token:
            valid, payload = worker_crypto.verify_and_consume_token_with_payload(token=token)
            if valid and payload:
                return True, payload.get("user_id")
            elif valid:
                return True, None

        # 3. Fallback for locally generated in-memory tokens (dev/test)
        self._cleanup_expired_tokens()
        entry = self.single_use_tokens.pop(token, None)
        if entry is None:
            return False, None
        expiry, user_id = entry
        if time.time() <= expiry:
            return True, user_id
        return False, None

    def _cleanup_expired_tokens(self):
        now = time.time()
        expired = [t for t, (exp, _) in self.single_use_tokens.items() if exp < now]
        for t in expired:
            self.single_use_tokens.pop(t, None)

    def validate_tracking_token(self, job_id: str, token: Optional[str]) -> bool:
        if not token or not job_id:
            return False
        expected = self.job_tracking_tokens.get(job_id)
        return expected is not None and secrets.compare_digest(expected, token)

    def invalidate_tracking_token(self, job_id: str):
        self.job_tracking_tokens.pop(job_id, None)
        if job_id in self.jobs:
            self.jobs[job_id].tracking_token = None

    def invalidate_tokens_for_container(self, container_id: str):
        affected = [jid for jid, job in self.jobs.items() if job.container_id == container_id]
        for jid in affected:
            self.invalidate_tracking_token(jid)

    def record_file_download(self, job_id: str, file_identifier: str) -> bool:
        """
        Records that a file was downloaded by the client.
        Only invalidates the tracking token when ALL files generated by the job
        have been downloaded.
        Returns True if all files have now been downloaded, False otherwise.
        """
        if job_id not in self.downloaded_files:
            self.downloaded_files[job_id] = set()

        self.downloaded_files[job_id].add(file_identifier)

        job = self.jobs.get(job_id)
        if not job:
            self.invalidate_tracking_token(job_id)
            return True

        # Normalize with known file IDs / filenames
        if job.files:
            for f in job.files:
                if f.file_id == file_identifier or f.filename == file_identifier:
                    self.downloaded_files[job_id].add(f.file_id)
                    self.downloaded_files[job_id].add(f.filename)

            required_ids = {f.file_id for f in job.files}
            if required_ids.issubset(self.downloaded_files[job_id]):
                logger.info(f"All {len(required_ids)} file(s) downloaded for job {job_id}. Invalidating tracking token.")
                self.invalidate_tracking_token(job_id)
                return True
            return False
        else:
            # Single file or default filename
            self.invalidate_tracking_token(job_id)
            return True

    def are_all_job_files_downloaded(self, job_id: str) -> bool:
        job = self.jobs.get(job_id)
        if not job or job.status != "completed":
            return False
        if not job.files:
            return job_id in self.downloaded_files
        required_ids = {f.file_id for f in job.files}
        downloaded = self.downloaded_files.get(job_id, set())
        return required_ids.issubset(downloaded)

    def are_all_container_jobs_downloaded(self, container_id: str) -> bool:
        container_jobs = [j for j in self.jobs.values() if j.container_id == container_id]
        if not container_jobs:
            return True
        # If any job is still running, container is not finished
        for j in container_jobs:
            if j.status not in ["completed", "failed", "cancelled"]:
                return False
            if j.status == "completed" and not self.are_all_job_files_downloaded(j.job_id):
                return False
        return True

    def get_active_jobs_count(self) -> int:
        return sum(
            1 for j in self.jobs.values()
            if j.status in ["pending", "starting_container", "installing_plugins", "downloading"]
        )

    async def create_job(
        self, request: JobCreateRequest, token_user_id: Optional[str] = None
    ) -> JobResponse:
        job_id = str(uuid.uuid4())
        tracking_token = secrets.token_urlsafe(32)
        self.job_tracking_tokens[job_id] = tracking_token
        now = datetime.datetime.now(datetime.timezone.utc)

        # Handle envelope-decrypted credentials if present
        effective_cookie = request.cookie_content
        effective_custom_args = list(request.custom_args or [])
        effective_plugins = list(request.plugins or [])
        decrypted_user_id = None

        if request.encrypted_credentials:
            from app.services.crypto import worker_crypto
            try:
                decrypted = worker_crypto.decrypt_envelope(
                    client_public_key_b64=request.encrypted_credentials.client_public_key,
                    nonce_b64=request.encrypted_credentials.nonce,
                    ciphertext_b64=request.encrypted_credentials.ciphertext,
                )
                logger.info(f"Successfully decrypted envelope credentials for job {job_id}")
                if "user_id" in decrypted and decrypted["user_id"]:
                    decrypted_user_id = decrypted["user_id"]
                if "cookie_content" in decrypted and decrypted["cookie_content"]:
                    effective_cookie = decrypted["cookie_content"]
                if "custom_args" in decrypted and decrypted["custom_args"]:
                    extra_args = decrypted["custom_args"]
                    if isinstance(extra_args, list):
                        effective_custom_args.extend(extra_args)
                if "plugins" in decrypted and decrypted["plugins"]:
                    extra_plugins = decrypted["plugins"]
                    if isinstance(extra_plugins, list):
                        for p in extra_plugins:
                            if p not in effective_plugins:
                                effective_plugins.append(p)
            except Exception as e:
                logger.error(f"Failed to decrypt envelope credentials for job {job_id}: {e}")
                job = JobResponse(
                    job_id=job_id,
                    user_id=token_user_id or request.user_id,
                    tracking_token=tracking_token,
                    url=request.url,
                    status="failed",
                    error=f"Envelope credential decryption failed: {e}",
                    plugins=request.plugins or [],
                    created_at=now,
                    completed_at=now,
                    logs=[f"Job created at {now.isoformat()}", f"Decryption error: {e}"],
                )
                self.jobs[job_id] = job
                return job

        # Determine effective user_id:
        # 1. Authoritative signed single-use token claim (token_user_id)
        # 2. Decrypted payload user_id
        # 3. Request user_id
        # 4. Fallback to a unique anonymous user ID (ensuring unauthenticated jobs never share containers)
        effective_user_id = (
            token_user_id
            or decrypted_user_id
            or request.user_id
            or f"anon-{uuid.uuid4().hex[:12]}"
        )

        job = JobResponse(
            job_id=job_id,
            user_id=effective_user_id,
            tracking_token=tracking_token,
            url=request.url,
            status="starting_container",
            plugins=effective_plugins,
            created_at=now,
            logs=[f"Job created at {now.isoformat()}"],
        )
        self.jobs[job_id] = job

        # Provision or retrieve runner container for this specific user
        try:
            runner = await docker_manager.get_or_create_runner(user_id=effective_user_id)
            job.container_id = runner.container_id
            job.container_name = runner.name
            job.logs.append(f"Assigned to user-specific runner container: {runner.name}")
            runner.active_jobs_count += 1
            runner.touch()

            # Create effective request for runner dispatch
            dispatch_req = JobCreateRequest(
                url=request.url,
                user_id=effective_user_id,
                cookie_content=effective_cookie,
                custom_args=effective_custom_args,
                output_template=request.output_template,
                format_selection=request.format_selection,
                plugins=effective_plugins,
            )

            # Forward download request to runner HTTP supervisor
            async_task = asyncio.create_task(
                self._dispatch_and_monitor(job_id, runner, dispatch_req)
            )
            self._sync_tasks[job_id] = async_task

        except Exception as e:
            logger.error(f"Failed to start job {job_id}: {e}", exc_info=True)
            job.status = "failed"
            job.error = str(e)
            job.completed_at = datetime.datetime.now(datetime.timezone.utc)
            job.logs.append(f"Job dispatch error: {e}")

        return job

    async def _dispatch_and_monitor(
        self, job_id: str, runner: RunnerContainerRecord, request: JobCreateRequest
    ):
        job = self.jobs[job_id]
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                payload = {
                    "url": request.url,
                    "cookie_content": request.cookie_content,
                    "custom_args": request.custom_args,
                    "output_template": request.output_template,
                    "format_selection": request.format_selection,
                    "plugins": request.plugins or [],
                }
                resp = await client.post(f"{runner.base_url}/download", json=payload)
                if resp.status_code not in [200, 202]:
                    raise RuntimeError(
                        f"Supervisor returned status {resp.status_code}: {resp.text}"
                    )

                task_data = resp.json()
                task_id = task_data["task_id"]
                job.task_id = task_id
                job.status = "downloading"
                job.logs.append(f"Supervisor task started with ID: {task_id}")

            # Poll status until finished
            while True:
                await asyncio.sleep(1.0)
                runner.touch()

                async with httpx.AsyncClient(timeout=5.0) as client:
                    resp = await client.get(f"{runner.base_url}/download/{job.task_id}")
                    if resp.status_code != 200:
                        continue

                    status_data = resp.json()
                    current_status = status_data.get("status")
                    if current_status:
                        job.status = current_status

                    job.progress_percent = status_data.get("progress_percent", 0.0)
                    job.downloaded_bytes = status_data.get("downloaded_bytes", 0)
                    job.total_bytes = status_data.get("total_bytes")
                    job.speed_bytes_per_sec = status_data.get("speed_bytes_per_sec")
                    job.eta_seconds = status_data.get("eta_seconds")
                    job.filename = status_data.get("filename")
                    
                    if status_data.get("logs"):
                        job.logs = status_data["logs"]

                    if current_status in ["completed", "failed", "cancelled"]:
                        job.error = status_data.get("error")
                        job.completed_at = datetime.datetime.now(datetime.timezone.utc)

                        # Process table of generated files
                        raw_files = status_data.get("files", [])
                        file_items: List[FileItemResponse] = []
                        for rf in raw_files:
                            fid = rf["file_id"]
                            fname = rf["filename"]
                            # Register in worker file map
                            self.file_map[fid] = (fname, runner.container_id)
                            self.file_map[fname] = (fname, runner.container_id)
                            file_items.append(
                                FileItemResponse(
                                    file_id=fid,
                                    filename=fname,
                                    size_bytes=rf["size_bytes"],
                                    mime_type=rf.get("mime_type", "application/octet-stream"),
                                    download_url=f"/api/v1/jobs/{job_id}/files/{fid}/download",
                                    modified_at=datetime.datetime.fromisoformat(
                                        rf["modified_at"]
                                    ) if isinstance(rf["modified_at"], str) else rf["modified_at"],
                                )
                            )

                        job.files = file_items
                        if file_items:
                            job.download_url = file_items[0].download_url
                            if not job.filename:
                                job.filename = file_items[0].filename
                        elif job.filename:
                            job.download_url = f"/api/v1/jobs/{job_id}/download"

                        # Generate cryptographic download receipt for orchestrator payout reporting
                        from app.services.announcer import announcer
                        from app.services.crypto import worker_crypto
                        if announcer.auth_token and announcer.worker_id:
                            job.receipt_token = worker_crypto.generate_download_receipt(
                                worker_id=announcer.worker_id,
                                auth_token=announcer.auth_token,
                                job_id=job_id,
                                user_id=job.user_id,
                                file_id=file_items[0].file_id if file_items else None,
                                bytes_downloaded=job.downloaded_bytes or None,
                            )

                        break

        except Exception as e:
            logger.error(f"Error during job monitoring for {job_id}: {e}", exc_info=True)
            job.status = "failed"
            job.error = str(e)
            job.completed_at = datetime.datetime.now(datetime.timezone.utc)
            job.logs.append(f"Monitor error: {e}")
        finally:
            runner.active_jobs_count = max(0, runner.active_jobs_count - 1)
            runner.touch()
            if runner.active_jobs_count == 0:
                runner.last_job_completed_at = time.time()
                runner.is_draining = True
                runner.draining_reason = "after_download_file_retention"

    async def cancel_job(self, job_id: str) -> bool:
        job = self.jobs.get(job_id)
        if not job or not job.container_id or not job.task_id:
            return False

        runner = docker_manager.get_container(job.container_id)
        if not runner:
            return False

        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.post(f"{runner.base_url}/download/{job.task_id}/cancel")
                if resp.status_code == 200:
                    job.status = "cancelled"
                    job.logs.append("Cancelled by user request.")
                    return True
        except Exception as e:
            logger.warning(f"Error cancelling job {job_id}: {e}")

        return False

    def get_job(self, job_id: str) -> Optional[JobResponse]:
        return self.jobs.get(job_id)

    def list_jobs(self) -> List[JobResponse]:
        return list(self.jobs.values())


job_service = JobService()

