import datetime
import hashlib
import mimetypes
import os
from pathlib import Path
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Query, status
from fastapi.responses import FileResponse, StreamingResponse
import httpx

from app.config import settings
from app.schemas import (
    ContainerInfoResponse,
    FileItemResponse,
    JobCreateRequest,
    JobResponse,
    PluginInstallRequest,
    PluginInstallResponse,
)
from app.services.docker_manager import docker_manager
from app.services.job_service import job_service

router = APIRouter(prefix="/api/v1", tags=["Jobs & Downloads"])


def _generate_hex_id(filename: str, filepath: Optional[str] = None) -> str:
    salt = ""
    if filepath and os.path.exists(filepath):
        salt = f":{os.path.getmtime(filepath)}:{os.path.getsize(filepath)}"
    return hashlib.sha256(f"{filename}{salt}".encode()).hexdigest()[:16]


@router.post(
    "/jobs",
    response_model=JobResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Create a yt-dlp download job",
    description="Spins up child yt-dlp container, installs any requested plugins, isolates cookie credentials, and tracks all generated files."
)
async def create_job(request: JobCreateRequest):
    return await job_service.create_job(request)


@router.get(
    "/jobs",
    response_model=List[JobResponse],
    summary="List all download jobs with their generated files table"
)
async def list_jobs():
    return job_service.list_jobs()


@router.get(
    "/jobs/{job_id}",
    response_model=JobResponse,
    summary="Get job status, progress, and table of generated files"
)
async def get_job(job_id: str):
    job = job_service.get_job(job_id)
    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found."
        )
    return job


@router.post(
    "/jobs/{job_id}/cancel",
    summary="Cancel a running download job"
)
async def cancel_job(job_id: str):
    success = await job_service.cancel_job(job_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Could not cancel job {job_id}."
        )
    return {"status": "success", "message": f"Job {job_id} cancelled."}


@router.get(
    "/jobs/{job_id}/download",
    summary="Download finished media file for a job (supports optional ?file_id=hex)"
)
async def download_job_file(
    job_id: str,
    file_id: Optional[str] = Query(None, description="Optional specific hex file ID from the job's files table")
):
    job = job_service.get_job(job_id)
    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found."
        )
    if job.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Job {job_id} is not completed (current status: {job.status})."
        )

    # If specific file_id requested
    target_filename = job.filename
    target_id = file_id

    if file_id and job.files:
        matching = [f for f in job.files if f.file_id == file_id]
        if matching:
            target_filename = matching[0].filename
            target_id = matching[0].file_id

    if not target_filename and job.files:
        target_filename = job.files[0].filename
        target_id = job.files[0].file_id

    if not target_filename:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No files generated by this job."
        )

    return await _stream_file_response(target_id or target_filename, target_filename, job.container_id)


@router.post(
    "/plugins/install",
    response_model=PluginInstallResponse,
    summary="Install Python plugin in yt-dlp runner container"
)
async def install_plugin(request: PluginInstallRequest):
    return await job_service.install_plugins(request)


@router.get(
    "/containers",
    response_model=List[ContainerInfoResponse],
    summary="List active runner containers and inactivity countdown"
)
async def list_containers():
    containers = await docker_manager.list_containers()
    result = []
    for c in containers:
        result.append(
            ContainerInfoResponse(
                container_id=c.container_id,
                name=c.name,
                status="running",
                ip_address=c.host_or_ip,
                endpoint_url=c.base_url,
                idle_seconds=c.idle_seconds,
                remaining_idle_seconds=c.remaining_idle_seconds,
                active_jobs=c.active_jobs_count,
                last_activity=datetime.datetime.fromtimestamp(
                    c.last_activity, tz=datetime.timezone.utc
                ),
            )
        )
    return result


@router.delete(
    "/containers/{container_id}",
    summary="Manually stop and remove runner container"
)
async def remove_container(container_id: str):
    removed = await docker_manager.stop_and_remove_container(container_id)
    if not removed:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Container {container_id} not found or could not be removed."
        )
    return {"status": "success", "message": f"Container {container_id} removed."}


@router.get(
    "/files",
    response_model=List[FileItemResponse],
    summary="Table of all downloaded files with hex file IDs and download URLs"
)
async def list_files():
    downloads_path = Path(settings.LOCAL_DOWNLOADS_PATH)
    file_items: List[FileItemResponse] = []

    # 1. Inspect local shared storage
    if downloads_path.exists():
        for f in downloads_path.iterdir():
            if f.is_file():
                stat = f.stat()
                fid = _generate_hex_id(f.name, str(f))
                mime_type, _ = mimetypes.guess_type(f.name)
                job_service.file_map[fid] = (f.name, None)
                file_items.append(
                    FileItemResponse(
                        file_id=fid,
                        filename=f.name,
                        size_bytes=stat.st_size,
                        mime_type=mime_type or "application/octet-stream",
                        download_url=f"/api/v1/files/{fid}/download",
                        modified_at=datetime.datetime.fromtimestamp(
                            stat.st_mtime, tz=datetime.timezone.utc
                        ),
                    )
                )

    # 2. If local empty or additionally query runner containers
    if not file_items:
        containers = await docker_manager.list_containers()
        for c in containers:
            try:
                c.touch()
                async with httpx.AsyncClient(timeout=3.0) as client:
                    resp = await client.get(f"{c.base_url}/files")
                    if resp.status_code == 200:
                        for rf in resp.json():
                            fid = rf["file_id"]
                            job_service.file_map[fid] = (rf["filename"], c.container_id)
                            file_items.append(
                                FileItemResponse(
                                    file_id=fid,
                                    filename=rf["filename"],
                                    size_bytes=rf["size_bytes"],
                                    mime_type=rf.get("mime_type", "application/octet-stream"),
                                    download_url=f"/api/v1/files/{fid}/download",
                                    modified_at=datetime.datetime.fromisoformat(
                                        rf["modified_at"]
                                    ) if isinstance(rf["modified_at"], str) else rf["modified_at"],
                                )
                            )
            except Exception:
                pass

    return file_items


@router.get(
    "/files/{file_id_or_name}/download",
    summary="Download/stream file identified by its hex file ID (or filename)"
)
@router.get(
    "/files/{file_id_or_name}",
    include_in_schema=False
)
async def stream_file(file_id_or_name: str):
    # Lookup in job service file map
    target_filename = file_id_or_name
    container_id = None

    if file_id_or_name in job_service.file_map:
        target_filename, container_id = job_service.file_map[file_id_or_name]

    return await _stream_file_response(file_id_or_name, target_filename, container_id)


async def _stream_file_response(
    identifier: str, filename: Optional[str] = None, container_id: Optional[str] = None
):
    # 1. Local path check
    downloads_path = Path(settings.LOCAL_DOWNLOADS_PATH)
    if filename:
        local_file = downloads_path / filename
        if local_file.is_file() and local_file.exists():
            return FileResponse(
                path=str(local_file),
                filename=filename,
                media_type="application/octet-stream",
            )

    # 2. Direct container lookup if known
    if container_id:
        runner = docker_manager.get_container(container_id)
        if runner:
            runner.touch()
            client = httpx.AsyncClient(timeout=None)
            req = client.build_request("GET", f"{runner.base_url}/files/{identifier}/download")
            r = await client.send(req, stream=True)
            if r.status_code == 200:
                headers = dict(r.headers)
                if filename and "content-disposition" not in [k.lower() for k in headers]:
                    headers["content-disposition"] = f'attachment; filename="{filename}"'
                return StreamingResponse(
                    r.aiter_raw(),
                    status_code=200,
                    headers=headers,
                    background=client.aclose,
                )
            await client.aclose()

    # 3. Fallback: Search all active runner containers
    containers = await docker_manager.list_containers()
    for c in containers:
        try:
            c.touch()
            client = httpx.AsyncClient(timeout=None)
            req = client.build_request("GET", f"{c.base_url}/files/{identifier}/download")
            r = await client.send(req, stream=True)
            if r.status_code == 200:
                headers = dict(r.headers)
                if filename and "content-disposition" not in [k.lower() for k in headers]:
                    headers["content-disposition"] = f'attachment; filename="{filename}"'
                return StreamingResponse(
                    r.aiter_raw(),
                    status_code=200,
                    headers=headers,
                    background=client.aclose,
                )
            await client.aclose()
        except Exception:
            pass

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"File '{identifier}' could not be located."
    )
